export const rowData = [
    {
        EmployeeId: 1,
        Name: 'Giorgio Parisi',
        Year: 2021,
        Company: 'Sapienza University',
        Country: 'Italy',
        CountryCode: 'ITA',
        Email: 'giorgio.parisi@mail.com',
        Rating: 89,
    },
    {
        EmployeeId: 2,
        Name: 'Klaus Hasselman',
        Year: 2021,
        Company: 'University of Hamburg',
        Country: 'Germany',
        CountryCode: 'DEU',
        Email: 'klaus.hasselman@yahoo.com',
        Rating: 74,
    },
    {
        EmployeeId: 3,
        Name: 'Syukor Manabe',
        Year: 2021,
        Company: 'Princeton University',
        Country: 'Japan',
        CountryCode: 'JPN',
        Email: 'syukor.manabe@outlook.com',
        Rating: 92,
    },
    {
        EmployeeId: 4,
        Name: 'Andrea Ghez',
        Year: 2020,
        Company: 'University of California',
        Country: 'United States',
        CountryCode: 'USA',
        Email: 'andrea.ghez@mail.com',
        Rating: 85,
    },
    {
        EmployeeId: 5,
        Name: 'Reinhard Genzel',
        Year: 2020,
        Company: 'Max Planck Institute',
        Country: 'Germany',
        CountryCode: 'DEU',
        Email: 'reinhard.genzel@mail.com',
        Rating: 68,
    },
    {
        EmployeeId: 6,
        Name: 'Roger Penrose',
        Year: 2020,
        Company: 'Cornell University',
        Country: 'United Kingdom',
        CountryCode: 'GBR',
        Email: 'roger.penrose@yahoo.com',
        Rating: 71,
    },
    {
        EmployeeId: 7,
        Name: 'Didier Queloz',
        Year: 2019,
        Company: 'University of Geneva',
        Country: 'Switzerland',
        CountryCode: 'CHE',
        Email: 'didier.queloz@mail.com',
        Rating: 87,
    },
    {
        EmployeeId: 8,
        Name: 'Michel Mayor',
        Year: 2019,
        Company: 'University of Geneva',
        Country: 'Switzerland',
        CountryCode: 'CHE',
        Email: 'michel.mayor@yahoo.com',
        Rating: 94,
    },
    {
        EmployeeId: 9,
        Name: 'Jim Peebles',
        Year: 2019,
        Company: 'Princeton University',
        Country: 'Canada',
        CountryCode: 'CAN',
        Email: 'jim.peebles@outlook.com',
        Rating: 66,
    },
];
